import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="xl:max-w-[1920px] mx-auto">
        <img src={`${process.env.NODE_ENV !== 'development' ? process.env.NEXT_PUBLIC_BASEPATH : ''}/img/B_현대IT_main_01.jpg`} alt="" />
        <img src={`${process.env.NODE_ENV !== 'development' ? process.env.NEXT_PUBLIC_BASEPATH : ''}/img/B_현대IT_main_02.jpg`} alt="" />
      </div>
    </>
  )
}

export default Home
