import type { NextPage } from 'next'
import Head from 'next/head'
import Img from 'comp/img'
import Section1 from 'comp/section1/section1'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>hyundai it - A안</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className='fixed top-0 left-0 z-[90] w-full'>
        <Img name="navi" type="svg" className="w-full" />
      </header>
      <main>
        <Section1 />
      </main>
      <footer>
        <Img name="footer" />
      </footer>
    </>
  )
}

export default Home
